### ISSUE TITLE
Feature Request: Export Paths

### ISSUE THREAD

**Issue by proxemics** [nfriend/inspirograph#57]
Would it be possible to allow for exporting of paths for use in something like Adobe Illustrator or similar vector based software? Maybe export as SVG or something? Great tool, just want to expand its use, thanks!

**Comment by nfriend** [comment]
Thanks for the suggestion, @proxemics.  At this point in time, exporting to a vector format would require a significant rewrite since the current implementation draws pixels to a `<canvas>` element.  It's also possible that an SVG-based implementation would have performance issues when the drawings get complex.

**Comment by proxemics** [comment]
Ah, that makes sense. Thanks for considering and thanks for the fantastic tool!
